services:
  server:
    build: ./server
    container_name: api_rest_servidor
    restart: always
    ports:
      - "5000:5000"
    networks:
      - distributed-network

  proxy:
    build: ./proxy
    container_name: proxy_interceptor
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - REST_SERVER_URL=http://server:5000/urls
      - CACHE_CAPACITY=5
      - THROTTLING_LIMIT=1.0
      - PYTHONUNBUFFERED=1
    networks:
      - distributed-network

  client-python:
    build: ./clients/python
    depends_on:
      - proxy
    environment:
      - PROXY_HOST=proxy
      - PROXY_PORT=8080
    networks:
      - distributed-network

networks:
  distributed-network:
    driver: bridge
