services:
  server:
    build: ./server
    container_name: api_rest_servidor
    restart: always
    ports:
      - "5050:5000"
    volumes:
      - ./config.txt:/server/config.txt:ro
    networks:
      - distributed-network

  proxy:
    build: ./proxy
    container_name: proxy_interceptor
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - PYTHONUNBUFFERED=1
      - DEMO_DELAY=${DEMO_DELAY:-0}
    volumes:
      - ./config.txt:/proxy/config.txt:ro
    networks:
      - distributed-network

  client-python:
    build: ./clients/python
    depends_on:
      - proxy
    volumes:
      - ./config.txt:/client/config.txt:ro
    networks:
      - distributed-network

  client-js:
    build: ./clientes/javascript
    depends_on:
      - proxy
    volumes:
      - ./config.txt:/client/config.txt:ro
    networks:
      - distributed-network

networks:
  distributed-network:
    driver: bridge
