services:
  server:
    build: ./server
    container_name: api_rest_servidor
    restart: always
    ports:
      - "5050:5000"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5000
    networks:
      - distributed-network

  proxy:
    build: ./proxy
    container_name: proxy_interceptor
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - PYTHONUNBUFFERED=1
      - DEMO_DELAY=${DEMO_DELAY:-0}
      - REST_SERVER_URL=http://server:5000/urls
      - PROXY_BIND_HOST=0.0.0.0
      - PROXY_BIND_PORT=8080
      - CACHE_CAPACITY=5
    networks:
      - distributed-network

  client-python:
    build: ./clients/python
    depends_on:
      - proxy
    environment:
      - PROXY_HOST=proxy
      - PROXY_PORT=8080
    networks:
      - distributed-network

  client-js:
    build: ./clients/javascript
    depends_on:
      - proxy
    environment:
      - PROXY_HOST=proxy
      - PROXY_PORT=8080
    networks:
      - distributed-network

networks:
  distributed-network:
    driver: bridge
